package pl.glownia.maciej.unlockenglishword.ui.unlock

// Map of english words as keys and their definitions as values
val allWordsAndItsDefinitionList: Map<String, String> = mapOf(
        "a" to "indefinite article",
        "abandon" to "to leave somebody, especially somebody you are responsible for, with no intention of returning",
        "ability" to "the fact that somebody/something is able to do something",
        "able" to "to have the skill, intelligence, opportunity, etc. needed to do something",
        "abortion" to "the deliberate ending of a pregnancy at an early stage",
        "about" to "on the subject of somebody/something; in connection with",
        "above" to "at or to a higher place or position than something/somebody",
        "abroad" to "in or to a foreign country",
        "absence" to "the fact of somebody being away from a place where they are usually expected to be; the occasion or period of time when somebody is away",
        "absolute" to "total and complete",
        "absolutely" to "used to emphasize that something is completely true",
        "absorb" to "to take in a liquid, gas or other substance from the surface or space around",
        "abuse" to "the use of something in a way that is wrong or harmful",
        "academic" to "connected with education, especially studying in schools and universities",
        "accept" to "to take willingly something that is offered; to say ‘yes’ to an offer, invitation, etc.",
        "access" to "the opportunity or right to use something or to see somebody/something",
        "accident" to "an unpleasant event, especially in a vehicle, that happens unexpectedly and causes injury or damage",
        "accompany" to "to travel or go somewhere with somebody/something",
        "accomplish" to "to succeed in doing or completing something",
        "according" to "to give somebody/something authority, status or a particular type of treatment",
        "account" to "an arrangement that somebody has with a bank, etc. to keep money there, take some out, etc.",
        "accurate" to "correct and true in every detail",
        "accuse" to "to say that somebody has done something wrong or is guilty of something",
        "achieve" to "... something to succeed in reaching a particular goal, status or standard, especially by making an effort for a long time",
        "achievement" to "a thing that somebody has done successfully, especially using their own effort and skill",
        "acid" to "a chemical, usually a liquid, that contains hydrogen and has a pH of less than seven",
        "acknowledge" to "to accept that something is true",
        "acquire" to "... something to gain something by your own efforts, ability or behaviour",
        "across" to "from one side to the other side of something",
        "act" to "to do something for a particular purpose or in order to deal with a situation",
        "action" to "the process of doing something in order to make something happen or to deal with a situation",
        "active" to "always busy doing things, especially physical activities",
        "activist" to "a person who works to achieve political or social change, especially as a member of an organization with particular aims",
        "activity" to "a thing that you do for interest or pleasure",
        "actor" to "a person who performs on the stage, on television or in films, especially as a profession",
        "actress" to "a woman who performs on the stage, on television or in films, especially as a profession",
        "actual" to "used to emphasize something that is real or exists in fact",
        "actually" to "used in speaking to emphasize a fact or a comment, or that something is really true",
        "ad" to "a notice, picture or film telling people about a product, job or service",
        "adapt" to "to change your behaviour in order to deal more successfully with a new situation",
        "add" to "to put something together with something else so as to increase the size, number, amount, etc.",
        "addition" to "a thing that is added to something else",
        "additional" to "more than was first mentioned or is usual",
        "address" to "details of where somebody lives or works and where letters, etc. can be sent",
        "adequate" to "enough in quantity, or good enough in quality, for a particular purpose or need",
        "adjust" to "to change something slightly to make it more suitable for a new set of conditions or to make it work better",
        "adjustment" to "a small change made to something in order to correct or improve it",
        "administration" to "the activities that are done in order to plan, organize and run a business, school or other institution",
        "administrator" to "a person whose job is to manage and organize the public or business affairs of a company or an institution, or a person who works in an office dealing with records, accounts, etc.",
        "admire" to "to respect somebody for what they have done or to respect their qualities",
        "admission" to "the act of accepting somebody into an institution, organization, etc.; the right to enter a place or to join an institution or organization",
        "admit" to "to agree, often unwillingly, that something is true",
        "adolescent" to "​a young person who is developing from a child into an adult",
        "adopt" to "to take somebody else’s child into your family and become its legal parent(s)",
        "adult" to "a fully grown person who is legally responsible for their actions",
        "advance" to "progress or a development in a particular activity or area of understanding",
        "advanced" to "having the most modern and recently developed ideas, methods, etc.",
        "advantage" to "a thing that helps you to be better or more successful than other people",
        "adventure" to "an unusual, exciting or dangerous experience, journey or series of events",
        "advertising" to "the activity and industry of advertising things to people on television, in newspapers, on the internet, etc.",
        "advice" to "an opinion or a suggestion about what somebody should do in a particular situation",
        "advise" to "to tell somebody what you think they should do in a particular situation",
        "adviser" to "a person who gives advice, especially somebody who knows a lot about a particular subject",
        "advocate" to "a person who supports or speaks in favour of somebody or of a public plan or action",
        "affair" to "in plural, events that are of public interest or political importance",
        "affect" to "to produce a change in somebody/something",
        "afford" to "(usually used with can, could or be able to, especially in negative sentences or questions) to have enough money to be able to buy or do something",
        "afraid" to "feeling fear; frightened because you think that you might be hurt or suffer",
        "African" to "of or connected with Africa",
        "African-American" to "a person from America who is a member of a group of people who have dark skin and whose ancestors came from Africa",
        "after" to "later than something; following something in time",
        "afternoon" to "the period of time from 12 o'clock in the middle of the day until about 6 o’clock in the evening",
        "again" to "one more time; on another occasion",
        "against" to "opposing or disagreeing with somebody/something",
        "age" to "the number of years that a person has lived or a thing has existed",
        "agency" to "a business or an organization that provides a particular service especially when representing other businesses or organizations",
        "agenda" to "a list of items to be discussed at a meeting",
        "agent" to "a person whose job is to act for, or manage the affairs of, other people in business, politics, etc.",
        "aggressive" to "angry, and behaving in a threatening way; ready to attack",
        "ago" to "used in expressions of time with the simple past tense to show how far in the past something happened",
        "agree" to "to have the same opinion as somebody; to say that you have the same opinion",
        "agreement" to "an arrangement, a promise or a contract made with somebody",
        "agricultural" to "connected with the science or practice of farming",
        "ah" to "used to express surprise, pleasure or sympathy, or when you disagree with somebody",
        "ahead" to "further forward in space or time; in front",
        "aid" to "money, food, etc. that is sent to help countries in difficult situations",
        "aide" to "a person who helps another person, especially a politician, in their job",
        "AIDS" to "a serious illness caused by a virus called HIV that attacks the body’s ability to resist infection (the abbreviation for ‘Acquired Immune Deficiency Syndrome’)",
        "aim" to "to try or plan to achieve something",
        "air" to "the mixture of gases that surrounds the earth and that we breathe",
        "aircraft" to "any vehicle that can fly and carry goods or passengers",
        "airline" to "a company that provides regular flights to take passengers and goods to different places",
        "airport" to "a place where planes land and take off and that has buildings for passengers to wait in",
        "album" to "a book in which you keep photographs, stamps, etc.",
        "alcohol" to "drinks such as beer, wine, etc. that can make people drunk",
        "alive" to "living; not dead",
        "all" to "(used with plural nouns. The noun may have the, this, that, my, her, his, etc. in front of it, or a number.) the whole number of",
        "alliance" to "an agreement between countries, political parties, etc. to work together in order to achieve something that they all want",
        "allow" to "to let somebody/something do something; to let something happen or be done"
)
